Endereco
JuliaFSO/cidadaos pull request #4
Opened 2021-07-19 18:39 UTC by JuliaFSO

Incluído routes e controller de endereço, e adicionado o formulário para salvar o endereço junto ao munícipe.

2021-07-19 20:10 UTC, gumiguelote requested changes
- Verificar esses primeiros comentários!
- Parabéns pelo progresso! Estamos caminhando.

Use a documentação do Rails ao seu favor rsrs

2021-07-19 20:10 UTC, gumiguelote commented on app/controllers/cidadaos_controller.rb
> +    redirect_to cidadao_path(@cidadao), notice: 'Munícipe adicionado com sucesso.'
Para as mensagens de erro, e demais textos da aplicação, da uma olhada nisso aqui: https://guides.rubyonrails.org/i18n.html

2021-07-19 20:10 UTC, gumiguelote commented on app/assets/stylesheets/pages/_form.scss
> +  font-family: Verdana, Geneva, Tahoma, sans-serif;
Vi essa mesma linha sendo repetida, ela poderia ser uma classe especifica para fonte. Oque você acha?

2021-07-19 20:10 UTC, gumiguelote commented on app/views/enderecos/_form.html.erb
> +                      label: "UF",
Seria uma boa, para já tratar no front, colocar um maxlenght nesse campo. Desta forma o usuário fica limitado a 2 caracteres para o estado/unidade federativa...
Ou se pensarmos melhor, será que esse campo, que seria para os estados, deveria ser um input de texto ou de seleção(select). Acredito que os estados são fixos e não mudam...
Oque você acha?

2021-07-19 22:42 UTC, ricardopacheco requested changes

2021-07-19 22:42 UTC, ricardopacheco commented on app/controllers/cidadaos_controller.rb
> +    @endereco = Endereco.new
Porque você está criando uma nova instância (objeto) endereço em um método show? Existe um formulário na tela de endereço?

Nesse caso me parece está errado ... como vc tem acesso ao objeto `@cidadao` pelo before_action,  você pode carregar o endereço dessa forma: `@endereco = @cidadao.endereco` (considerando que a relação entre as classes é endereço belongs_to cidadao). Quando existe uma associação (via models), isso faz com que o ActiveRecord carregue o objeto associado a partir do banco de dados (você consegue ver essa query sendo disparada a partir do log da aplicação).

2021-07-19 22:42 UTC, ricardopacheco commented on test/controllers/enderecos_controller_test.rb
> +class EnderecosControllerTest < ActionDispatch::IntegrationTest
Você vai utilizar Test::Unit (esse caso criado) ou, rspec?

Caso use test::unit está ok por hora, se você vai usar RSpec recomendo a remoção desse arquivo.

2021-07-19 22:42 UTC, ricardopacheco commented on config/routes.rb
> +  resources :cidadaos, except: :destroy do
Excelente! 👍

2021-07-19 22:42 UTC, ricardopacheco commented on config/routes.rb
> +    resources :enderecos, only: [:new, :create, :edit, :update]
Style (opcional): resources :enderecos, only: [:new, :create, :edit, :update]

Pode ser usado também `resources :enderecos, except: [:destroy]`

2021-07-19 22:42 UTC, ricardopacheco commented on config/application.rb
> +    Date::DATE_FORMATS[:default] = "%d/%m/%Y"
Realmente eu recomendo você remover essa linha! Caso queira usar essa configuração assim (anti-pattern), você deveria mover para um arquivo de initializer. exemplo: `config/initializers/date.rb`. config/application.rb são configurações a nível de framework!

O jeito mais correto seriam duas formas direto em código.

1. Utilizando I18n.l. Exemplo: `I18n.(@cidadao.created_at, format: :default)` e configurar um arquivo de locale com a parte para tipos de date/datetime: https://guides.rubyonrails.org/i18n.html#adding-date-time-formats

2. Pode utilizar diretamente no código o método do Ruby [strftime](https://apidock.com/ruby/DateTime/strftime). Esse método existe em muitas linguagens de programação, não apenas em Ruby. Serve para converter strings em formato de data específicos.

2021-07-19 22:42 UTC, ricardopacheco commented on app/views/enderecos/new.html.erb
> +
Deixar apenas uma linha em branco após o final de um arquivo (rubocop, guidelines). Remover o restante.

2021-07-19 22:42 UTC, ricardopacheco commented on app/views/cidadaos/show.html.erb
> +
Deixar apenas uma linha em branco após o final de um arquivo (rubocop, guidelines). Remover o restante.

2021-07-19 22:44 UTC, ricardopacheco commented
O CR que fiz contém um anti-pattern (alteração de arquivo de configuração do framework com info para formatação de data). Isso quebra o princípio de responsabilidade única (cada coisa deve fazer apenas uma coisa).

O framework carrega GLOBALMENTE essa configuração. Caso outros devs tentem seguir a convenção de linguagem (strftime) ou o correto (I18n/I18l) sofrerá override a nível de camada de aplicação, podendo entender isso com um bug do framework (o que seria incorreto).

2021-07-20 10:07 UTC, italopires requested changes

2021-07-20 10:07 UTC, italopires commented on app/controllers/enderecos_controller.rb
> +    @cidadao = Cidadao.find(params[:cidadao_id])
Essa linha se repete na linha 8, implementaria um `before_action` e moveria essa linha para um metodo privado.

2021-07-20 10:07 UTC, italopires commented on app/controllers/enderecos_controller.rb
> +      redirect_to cidadao_path(@cidadao)
Adicionaria mensagens com i18n

2021-07-20 10:07 UTC, italopires commented on app/views/cidadaos/_form.html.erb
> +                    placeholder: "Nome completo",
Seria ótimo ter todos esses labels em I18n do model

2021-07-20 10:07 UTC, italopires commented on app/views/cidadaos/edit.html.erb
> +    <h2>Editar dados do munícipe</h2>
I18n

2021-07-20 10:07 UTC, italopires commented on app/views/enderecos/_form.html.erb
> +   <%= simple_form_for [@cidadao, @endereco] do |f| %>
Serial legal ajustar a identação desse arquivo. A linha um deveria começar no primeiro caractere de espaço, a linha dois com uma identação de 2 caracteres

2021-07-20 10:07 UTC, italopires commented on app/controllers/enderecos_controller.rb
> +class EnderecosController < ApplicationController
Criaria testes para esse controller

2021-07-20 10:07 UTC, italopires commented on app/controllers/cidadaos_controller.rb
> +  def show
Criaria testes para esse controller

2021-07-20 17:15 UTC, gumiguelote approved these changes
- Aprovado!! Bom trabalho!

2021-07-22 16:49 UTC, gumiguelote requested changes
- Da uma olhada nos comentários

2021-07-22 16:49 UTC, gumiguelote commented on config/locales/pt-BR.yml
>        last_name: ["Aguiar",  "Albuquerque",  "Almada",  "Almeida",  "Álvares",  "Alves",  "Ambrósio",  "Amoreira",  "Antena",  "Antunes",  "Aparício",  "Aragão",  "Arantes",  "Araújo",  "Aroeira",  "
@JuliaFSO Conta pra gente, qual seria essa abordagem

2021-07-22 16:49 UTC, gumiguelote commented on db/seeds.rb
>      cep: Faker::Address.postcode,
Verifica a documentação do FAKER, acredito que tenha CEP la, ao inves de postcode (americano)

2021-07-27 17:30 UTC, JuliaFSO reviewed
O faker de cep que encontrei estava dando erro, acabei resolvendo de outra forma.

2021-07-27 17:30 UTC, JuliaFSO commented on config/locales/pt-BR.yml
>        last_name: ["Aguiar",  "Albuquerque",  "Almada",  "Almeida",  "Álvares",  "Alves",  "Ambrósio",  "Amoreira",  "Antena",  "Antunes",  "Aparício",  "Aragão",  "Arantes",  "Araújo",  "Aroeira",  "
Achei essa documentação de faker, numa versão brasileira para quando eu chamar o faker ele seleciona esses ao invés dos americanos, achei interessante por isso apesar de ficar com o código poluído. =X

2021-07-27 18:12 UTC, gumiguelote commented on app/assets/stylesheets/components/_fonts.scss
> +    font-family: 'Roboto', sans-serif;
é uma ótima pratica, colocar outras fonts, caso a primeira falhe ou não seja encontrada.

2021-07-27 18:12 UTC, gumiguelote commented on app/assets/stylesheets/components/_fonts.scss
> +    font-family: 'Roboto', sans-serif;
Desta forma:
![image](https://user-images.githubusercontent.com/25744569/127206159-69183c8f-1d09-463f-be35-b2b8ebbcf2f6.png)

2021-07-27 18:21 UTC, gumiguelote commented on db/seeds.rb
>  20.times do
Acredito que seria legal adicionar idades, desde crianças até muito idosos

2021-07-27 18:32 UTC, gumiguelote requested changes
Muito bom o progresso!
De uma olhada nos comenários!

2021-07-27 18:32 UTC, gumiguelote commented on db/seeds.rb
>    file = URI.open('https://source.unsplash.com/featured/?portrait')
Isso aqui vai gerar uma requisição assíncrona durante o processo, é uma boa opção? Eu acredito uma imagem de placeholder, já serviria. Podendo ser reutilizada após como placeholder da imagem do cadastro do munícipe

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/passwords/edit.html.erb
> +                    label: "Nova senha",
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/passwords/edit.html.erb
> +                    hint: ("#{@minimum_password_length} caracteres mínimos" if @minimum_password_length),
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/passwords/edit.html.erb
> +                    input_html: { autocomplete: "nova senha" } %>
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/passwords/edit.html.erb
> +                    label: "Confirme sua nova senha",
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/passwords/edit.html.erb
> +                    input_html: { autocomplete: "nova senha" } %>
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/passwords/edit.html.erb
> +        <%= f.button :submit, "MUDAR MINHA SENHA" %>
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/passwords/new.html.erb
> +      <div class="align-self-center"><h1 class="text-center mt-2">MUNÍCIPES</h1></div>
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/passwords/new.html.erb
> +      <div class="align-self-center"><h2 class="text-center mt-2"><h2>Esqueceu sua senha?</h2></div>
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/passwords/new.html.erb
> +      <%= f.button :submit, "Me envie instruções de redefinição de senha" %>
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/shared/_links.html.erb
> +  <%= link_to "Cadastre-se", new_registration_path(resource_name) %><br />
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/shared/_links.html.erb
> +  <%= link_to "Login", new_session_path(resource_name) %><br />
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/shared/_links.html.erb
> +  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %><br />
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/shared/_links.html.erb
> +  <%= link_to "Não recebeu instruções de confirmação?", new_confirmation_path(resource_name) %><br />
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/shared/_links.html.erb
> +  <%= link_to "Não recebeu instruções de desbloqueio?", new_unlock_path(resource_name) %><br />
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/devise/shared/_links.html.erb
> +    <%= link_to "Entrar com #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/cidadaos/_form.html.erb
> +                      placeholder: "Rua, Av., Trav.",
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/cidadaos/_form.html.erb
>                        label: "Logradouro",
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/cidadaos/_form.html.erb
> +                    collection: [['Ativo', true], ['Inativo', false]] %>
Acredito que essas opções deveriam ser responsabilidade do backend, imagina se são adicionados novos status, seria somente alterar no backend

2021-07-27 18:32 UTC, gumiguelote commented on app/views/cidadaos/show.html.erb
> +        <div class="col"><h5>Status</h5><p><%= @cidadao.status? ? 'Ativo' : 'Inativo' %></p></div>
Veja que o seguinte trecho que aparece no index,html é bem parecido a este:

<td><%= cidadao.status? ? 'Ativo' : 'Inativo' %></th>

2021-07-27 18:32 UTC, gumiguelote commented on app/views/cidadaos/show.html.erb
>        <a class="btn btn-home" href='<%= edit_cidadao_path(@cidadao) %>' role="button">Editar Munícipe</a>
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/cidadaos/_form.html.erb
> +        <%= f.button :submit, "Adicionar munícipe", class:"btn-home" %>
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/cidadaos/show.html.erb
>      <div class="p-2 flex-grow-1"><h1>MUNÍCIPE</h1></div>
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/views/cidadaos/new.html.erb
>      <h2>Preencha os dados do munícipe</h2>
Adicionar i18n

2021-07-27 18:32 UTC, gumiguelote commented on app/javascript/packs/application.js
> +//require('packs/busca_cep')
Caso não va utilizar o trecho, ao inves de comentar, remova do codigo. Isso deixa seu código mais limpo e não gera dúvidas futuras

2021-07-27 18:32 UTC, gumiguelote commented on Gemfile
>  gem 'devise'
Seria uma excelente pratica, colocar as versões especificas para todas as gems utilizadas.

2021-07-29 16:38 UTC, merged